hand_type: "right"
num_joints: 20
default_dof_pos: [0.02642133, 0.15084561, 0.23259762, 0.23259762, 
    0.16659025, 0.5, 0.23259762, 0.23259762, 
    0.16659025, 0.5, 0.23259762, 0.23259762,
    0.16659025, 0.5, 0.23259762, 0.23259762, 
    0.16659025, 0.5, 0.23259762, 0.23259762]
hardware_joint_is_reverse: [0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0]

real_to_sim_piecewise_joint_mapping: [1] # identity mapping
sim_joint_limited_fraction: [1,1,1,1, 1,1,1,1, 1,1,1,1, 1,1,1,1, 1,1,1,1] # full range

isaac_hand_dof_lower_limits: [-0.0448, -0.1659, -0.4932, -0.4932, -0.3270, -0.4950, -0.4932, -0.4932,
        -0.3270, -0.4950, -0.4932, -0.4932, -0.3270, -0.4950, -0.4932, -0.4932,
        -0.3270, -0.4950, -0.4932, -0.4932]
isaac_hand_dof_upper_limits: [1.6508, 0.9339, 1.6272, 1.6272, 1.6359, 0.4950, 1.6272, 1.6272, 1.6359,
        0.4950, 1.6272, 1.6272, 1.6359, 0.4950, 1.6272, 1.6272, 1.6359, 0.4950,
        1.6272, 1.6272]
isaac_active_hand_dof_names: ["finger1_joint1", "finger1_joint2", "finger1_joint3", "finger1_joint4", 
    "finger2_joint1", "finger2_joint2", "finger2_joint3", "finger2_joint4", 
    "finger3_joint1", "finger3_joint2", "finger3_joint3", "finger3_joint4", 
    "finger4_joint1", "finger4_joint2", "finger4_joint3", "finger4_joint4", 
    "finger5_joint1", "finger5_joint2", "finger5_joint3", "finger5_joint4"]
hardware_active_hand_dof_names: ["finger1_joint1", "finger1_joint2", "finger1_joint3", "finger1_joint4", 
    "finger2_joint1", "finger2_joint2", "finger2_joint3", "finger2_joint4", 
    "finger3_joint1", "finger3_joint2", "finger3_joint3", "finger3_joint4", 
    "finger4_joint1", "finger4_joint2", "finger4_joint3", "finger4_joint4", 
    "finger5_joint1", "finger5_joint2", "finger5_joint3", "finger5_joint4"]